### ISSUE TITLE
系统上禁止这个脚本的运行

### ISSUE THREAD

**Issue by liuyunzyj** [zhangdaren/wepy-to-uniapp#1]
![image](https://user-images.githubusercontent.com/40293335/66632975-503eda00-ec3c-11e9-9043-091d7a49b9a4.png)
到
![image](https://user-images.githubusercontent.com/40293335/66633064-82e8d280-ec3c-11e9-98fa-866a1759f475.png)
尝试使用直接运行etu.ps1,弹出powershell后又马上关闭了
系统：win 10

**Comment by zhangdaren** [comment]
看起来是权限不够，请参考：https://www.jianshu.com/p/be148bdbe8c2
 
------------------
不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！


 




------------------ 原始邮件 ------------------
发件人: "liuyunzyj"<notifications@github.com>; 
发送时间: 2019年10月11日(星期五) 下午3:35
收件人: "zhangdaren/wepy-to-uniapp"<wepy-to-uniapp@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [zhangdaren/wepy-to-uniapp] 系统上禁止这个脚本的运行 (#1)





 到
 
 尝试使用直接运行etu.ps1,弹出powershell后又马上关闭了
 系统：win 10
 
&mdash;

**Comment by liuyunzyj** [comment]
@zhangdaren 还是不行啊
![image](https://user-images.githubusercontent.com/40293335/66635108-0dcbcc00-ec41-11e9-8172-127d41c2f621.png)

**Comment by zhangdaren** [comment]
上面有提示：”请以管理员身份运行“
 
------------------
不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！


 




------------------ 原始邮件 ------------------
发件人: "liuyunzyj"<notifications@github.com>; 
发送时间: 2019年10月11日(星期五) 下午4:06
收件人: "zhangdaren/wepy-to-uniapp"<wepy-to-uniapp@noreply.github.com>; 
抄送: "张鹏"<375890534@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [zhangdaren/wepy-to-uniapp] 系统上禁止这个脚本的运行 (#1)




@zhangdaren 还是不行啊

**Comment by liuyunzyj** [comment]
@zhangdaren 
错误：![image](https://user-images.githubusercontent.com/40293335/66635709-6059b800-ec42-11e9-8bb0-bfc9a09def39.png)

**Comment by zhangdaren** [comment]
随便弄一个mainifest.json进去再试试
 
------------------
不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！


 




------------------ 原始邮件 ------------------
发件人: "liuyunzyj"<notifications@github.com>; 
发送时间: 2019年10月11日(星期五) 下午4:16
收件人: "zhangdaren/wepy-to-uniapp"<wepy-to-uniapp@noreply.github.com>; 
抄送: "张鹏"<375890534@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [zhangdaren/wepy-to-uniapp] 系统上禁止这个脚本的运行 (#1)




@zhangdaren
 错误：
 
&mdash;

**Comment by liuyunzyj** [comment]
@zhangdaren 还是一样，是我放的位置不对？
![image](https://user-images.githubusercontent.com/40293335/66636296-82076f00-ec43-11e9-88a1-bedc88604d3f.png)

**Comment by zhangdaren** [comment]
放src下
 
------------------
不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！


 




------------------ 原始邮件 ------------------
发件人: "liuyunzyj"<notifications@github.com>; 
发送时间: 2019年10月11日(星期五) 下午4:24
收件人: "zhangdaren/wepy-to-uniapp"<wepy-to-uniapp@noreply.github.com>; 
抄送: "张鹏"<375890534@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [zhangdaren/wepy-to-uniapp] 系统上禁止这个脚本的运行 (#1)




@zhangdaren 还是一样，是我放的位置不对？
 
 
&mdash;

**Comment by liuyunzyj** [comment]
@zhangdaren 还是不行
![image](https://user-images.githubusercontent.com/40293335/66636535-f93d0300-ec43-11e9-9989-42ceffb0bf7c.png)

**Comment by liuyunzyj** [comment]
还是一样
还是一样：是不是我放的位置不对呢？




------------------ 原始邮件 ------------------
发件人: "zhangdaren"<notifications@github.com>;
发送时间: 2019年10月11日(星期五) 下午4:18
收件人: "zhangdaren/wepy-to-uniapp"<wepy-to-uniapp@noreply.github.com>;
抄送: "蒗，，得妮♡"<1694382922@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zhangdaren/wepy-to-uniapp] 系统上禁止这个脚本的运行 (#1)



随便弄一个mainifest.json进去再试试 
   
 ------------------ 
 不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！ 
 
 
   
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "liuyunzyj"<notifications@github.com>;  
 发送时间: 2019年10月11日(星期五) 下午4:16 
 收件人: "zhangdaren/wepy-to-uniapp"<wepy-to-uniapp@noreply.github.com>;  
 抄送: "张鹏"<375890534@qq.com>; "Mention"<mention@noreply.github.com>;  
 主题: Re: [zhangdaren/wepy-to-uniapp] 系统上禁止这个脚本的运行 (#1) 
 
 
 
 
 @zhangdaren 
  错误： 
   
 &mdash;

**Comment by zhangdaren** [comment]
这个是我的锅，居然没发现。。。
 
------------------
不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！


 




------------------ 原始邮件 ------------------
发件人: "liuyunzyj"<notifications@github.com>; 
发送时间: 2019年10月11日(星期五) 下午4:27
收件人: "zhangdaren/wepy-to-uniapp"<wepy-to-uniapp@noreply.github.com>; 
抄送: "张鹏"<375890534@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [zhangdaren/wepy-to-uniapp] 系统上禁止这个脚本的运行 (#1)




@zhangdaren 还是不行
 
 
&mdash;

**Comment by zhangdaren** [comment]
更新一下再试试吧。  npm update wepy-to-uniapp -g
 
------------------
不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！


 




------------------ 原始邮件 ------------------
发件人: "liuyunzyj"<notifications@github.com>; 
发送时间: 2019年10月11日(星期五) 下午4:28
收件人: "zhangdaren/wepy-to-uniapp"<wepy-to-uniapp@noreply.github.com>; 
抄送: "张鹏"<375890534@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [zhangdaren/wepy-to-uniapp] 系统上禁止这个脚本的运行 (#1)



还是一样 
 还是一样：是不是我放的位置不对呢？ 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "zhangdaren"<notifications@github.com>; 
 发送时间: 2019年10月11日(星期五) 下午4:18 
 收件人: "zhangdaren/wepy-to-uniapp"<wepy-to-uniapp@noreply.github.com>; 
 抄送: "蒗，，得妮♡"<1694382922@qq.com>;"Author"<author@noreply.github.com>; 
 主题: Re: [zhangdaren/wepy-to-uniapp] 系统上禁止这个脚本的运行 (#1) 
 
 
 
 随便弄一个mainifest.json进去再试试  
     
  ------------------  
  不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！  
   
   
     
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "liuyunzyj"<notifications@github.com>;   
  发送时间: 2019年10月11日(星期五) 下午4:16  
  收件人: "zhangdaren/wepy-to-uniapp"<wepy-to-uniapp@noreply.github.com>;   
  抄送: "张鹏"<375890534@qq.com>; "Mention"<mention@noreply.github.com>;   
  主题: Re: [zhangdaren/wepy-to-uniapp] 系统上禁止这个脚本的运行 (#1)  
   
   
   
   
  @zhangdaren  
   错误：  
     
  &mdash;  
  You are receiving this because you were mentioned.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
&mdash;

**Comment by liuyunzyj** [comment]
@zhangdaren 更新后的错误：
![image](https://user-images.githubusercontent.com/40293335/66637494-b8de8480-ec45-11e9-8557-b9a6cf896c6d.png)

**Comment by zhangdaren** [comment]
我把那个文件干掉了，再更新了一版，这个应该不影响后续呗
 
------------------
不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！


 




------------------ 原始邮件 ------------------
发件人: "liuyunzyj"<notifications@github.com>; 
发送时间: 2019年10月11日(星期五) 下午4:39
收件人: "zhangdaren/wepy-to-uniapp"<wepy-to-uniapp@noreply.github.com>; 
抄送: "张鹏"<375890534@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [zhangdaren/wepy-to-uniapp] 系统上禁止这个脚本的运行 (#1)




@zhangdaren 更新后的错误：
 
 
&mdash;

**Comment by liuyunzyj** [comment]
@zhangdaren 错误
![image](https://user-images.githubusercontent.com/40293335/66638801-37d4bc80-ec48-11e9-991f-2e226ad076e0.png)

**Comment by liuyunzyj** [comment]
@zhangdaren 不论是执行npm run build:mp-alipay  或者是 npm run build:mp-weixin都会出现上面的那个错误

**Comment by zhangdaren** [comment]
看起来是语法错误，贴一下list.vue看看

 
------------------
不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！


 




------------------ 原始邮件 ------------------
发件人: "liuyunzyj"<notifications@github.com>; 
发送时间: 2019年10月11日(星期五) 下午4:57
收件人: "zhangdaren/wepy-to-uniapp"<wepy-to-uniapp@noreply.github.com>; 
抄送: "张鹏"<375890534@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [zhangdaren/wepy-to-uniapp] 系统上禁止这个脚本的运行 (#1)




@zhangdaren 错误
 
 
&mdash;

**Comment by liuyunzyj** [comment]
@zhangdaren 那个问题解决了，应该是编译的时候“”的问题导致的，后续又出了一个这样的问题
![image](https://user-images.githubusercontent.com/40293335/66640555-c3038180-ec4b-11e9-98b7-c0d089a6bacd.png)
![image](https://user-images.githubusercontent.com/40293335/66640600-d3b3f780-ec4b-11e9-98af-7e763be5a6bf.png)

**Comment by zhangdaren** [comment]
需要安装在目录下，运行npm i less-loader
 
------------------
不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！


 




------------------ 原始邮件 ------------------
发件人: "liuyunzyj"<notifications@github.com>; 
发送时间: 2019年10月11日(星期五) 下午5:23
收件人: "zhangdaren/wepy-to-uniapp"<wepy-to-uniapp@noreply.github.com>; 
抄送: "张鹏"<375890534@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [zhangdaren/wepy-to-uniapp] 系统上禁止这个脚本的运行 (#1)




@zhangdaren 那个问题解决了，应该是编译的时候“”的问题导致的，后续又出了一个这样的问题
 
 
 
&mdash;

**Comment by liuyunzyj** [comment]
安装后编译更加错误一堆，是什么东西没有正确引用吗
![image](https://user-images.githubusercontent.com/40293335/66640886-50df6c80-ec4c-11e9-87f6-1e41167b206e.png)
![image](https://user-images.githubusercontent.com/40293335/66640898-563cb700-ec4c-11e9-9922-f7ef12a7b4d1.png)
![image](https://user-images.githubusercontent.com/40293335/66640927-618fe280-ec4c-11e9-8f80-4b06910a5354.png)

**Comment by zhangdaren** [comment]
你可以按提示来嘛，，上面有提示  cannot find module "less"，没有安装less，安装一下。less还好，sass就有点麻烦了。后面我可能会逆转换为hbuilderx项目，而不是现在的vue项目。


另外，提示一下，这个转换坑还是有很多要填的，，转换的项目，仅供参考。。。
 
------------------
不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！


 




------------------ 原始邮件 ------------------
发件人: "liuyunzyj"<notifications@github.com>; 
发送时间: 2019年10月11日(星期五) 下午5:27
收件人: "zhangdaren/wepy-to-uniapp"<wepy-to-uniapp@noreply.github.com>; 
抄送: "张鹏"<375890534@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [zhangdaren/wepy-to-uniapp] 系统上禁止这个脚本的运行 (#1)




安装后编译更加错误一堆，是什么东西没有正确引用吗
 
 
 
 
&mdash;

**Comment by liuyunzyj** [comment]
装了也还是这个问题，待会我将整个包都删除在试一试吧------------------ 原始邮件 ------------------
发件人: "zhangdaren"<notifications@github.com>
发送时间: 2019年10月11日(星期五) 下午5:31
收件人: "zhangdaren/wepy-to-uniapp"<wepy-to-uniapp@noreply.github.com>;
抄送: "liuyunzyj"<1694382922@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zhangdaren/wepy-to-uniapp] 系统上禁止这个脚本的运行 (#1)


你可以按提示来嘛，，上面有提示  cannot find module "less"，没有安装less，安装一下。less还好，sass就有点麻烦了。后面我可能会逆转换为hbuilderx项目，而不是现在的vue项目。 
 
 
 另外，提示一下，这个转换坑还是有很多要填的，，转换的项目，仅供参考。。。 
   
 ------------------ 
 不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！ 
 
 
   
 
 
 
 
 ------------------ 原始邮&#x4EF6; ------------------ 
 发&#x4EF6;人: "liuyunzyj"<notifications@github.com>;  
 发送时间: 2019年10月11日(星期五) 下午5:27 
 收&#x4EF6;人: "zhangdaren/wepy-to-uniapp"<wepy-to-uniapp@noreply.github.com>;  
 抄送: "张鹏"<375890534@qq.com>; "Mention"<mention@noreply.github.com>;  
 主题: Re: [zhangdaren/wepy-to-uniapp] 系统上禁止这个脚本的运行 (#1) 
 
 
 
 
 安装后编译更加错误一堆，是什么东西没有正确引用吗 
   
   
   
   
 &mdash; 
 You are receiving this because you were mentioned. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
&mdash;

**Comment by liuyunzyj** [comment]
@zhangdaren 发现转 了后this都拿不到了，
![image](https://user-images.githubusercontent.com/40293335/66695370-52b03b00-ecf3-11e9-91df-051177e9082f.png)
![image](https://user-images.githubusercontent.com/40293335/66695371-5774ef00-ecf3-11e9-848b-8c80db712496.png)

**Comment by liuyunzyj** [comment]
![image](https://user-images.githubusercontent.com/40293335/66695429-ee41ab80-ecf3-11e9-952f-ce24222b7199.png)
![image](https://user-images.githubusercontent.com/40293335/66695434-f4378c80-ecf3-11e9-8699-c0cca7b2ac99.png)
![image](https://user-images.githubusercontent.com/40293335/66695439-fd285e00-ecf3-11e9-8733-2557c1c4544e.png)

**Comment by zhangdaren** [comment]
> @zhangdaren 发现转 了后this都拿不到了，
> ![image](https://user-images.githubusercontent.com/40293335/66695370-52b03b00-ecf3-11e9-91df-051177e9082f.png)
> ![image](https://user-images.githubusercontent.com/40293335/66695371-5774ef00-ecf3-11e9-848b-8c80db712496.png)
这个看起来是没有setData()这个函数，我后续把它加上。

可以先手动加上：

`setData:function(obj){    
    let that = this;    
    let keys = [];  
    let val,data;  
    Object.keys(obj).forEach(function(key){  
         keys = key.split('.');  
         val = obj[key];  
         data = that.$data;  
         keys.forEach(function(key2,index){  
             if(index+1 == keys.length){  
                 that.$set(data,key2,val);  
             }else{  
                 if(!data[key2]){  
                    that.$set(data,key2,{});  
                 }  
             }  
             data = data[key2];  
         })  
    });  
}`

出处：https://ask.dcloud.net.cn/article/35020

**Comment by zhangdaren** [comment]
回复this为undefined：
如果根节点上面的函数没法使用箭头函数了，是跟methods平齐的函数吗？

**Comment by tangcaiyue** [comment]
TypeError: initAutoImportComponents is not a function
![image](https://user-images.githubusercontent.com/15120864/76698406-79790000-66dd-11ea-92ce-a3bc7876c2aa.png)

**Comment by tangcaiyue** [comment]
$ cross-env NODE_ENV=development UNI_PLATFORM=h5 vue-cli-service uni-serve
请注意运行模式下，因日志输出、sourcemap以及未压缩源码等原因，性能和包体积，均不及发行模式。
/Users/tangna/2020/node_modules/@dcloudio/vue-cli-plugin-uni/lib/env.js:381
initAutoImportComponents(pagesJsonObj.easycom)
^

TypeError: initAutoImportComponents is not a function
    at Object.<anonymous> (/Users/tangna/2020/node_modules/@dcloudio/vue-cli-plugin-uni/lib/env.js:381:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/tangna/2020/node_modules/@dcloudio/vue-cli-plugin-uni/index.js:6:5)
    at Module._compile (module.js:653:30)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c cross-env NODE_ENV=development UNI_PLATFORM=h5 vue-cli-service uni-serve

**Comment by zhangdaren** [comment]
这种没遇到过，似乎是编译时uni报的错
